FROM node:22.5.1-bullseye-slim 

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

WORKDIR /usr/src/app/client
COPY client/package*.json ./
RUN npm install

WORKDIR /usr/src/app

EXPOSE 5000 3000

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]